enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[strava]
enabled = true
patches-source = "ReVanced/revanced-patches"
cli-source = "inotia00/revanced-cli"
build-mode = "apk"
arch = "both"
version = "latest"
uptodown-dlurl = "https://strava.en.uptodown.com/android"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-run-bike-hike-2"

[strava-beta]
enabled = true
patches-source = "ReVanced/revanced-patches"
cli-source = "inotia00/revanced-cli"
build-mode = "apk"
arch = "both"
version = "beta"
uptodown-dlurl = "https://strava.en.uptodown.com/android"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-run-bike-hike-2"

[strava-magisk]
enabled = true
patches-source = "ReVanced/revanced-patches"
cli-source = "inotia00/revanced-cli"
build-mode = "module"
arch = "both"
version = "latest"
uptodown-dlurl = "https://strava.en.uptodown.com/android"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-run-bike-hike-2"

[strava-magisk-beta]
enabled = true
patches-source = "ReVanced/revanced-patches"
cli-source = "inotia00/revanced-cli"
build-mode = "module"
arch = "both"
version = "beta"
uptodown-dlurl = "https://strava.en.uptodown.com/android"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-run-bike-hike-2"
